# ---------------- Database Configuration ----------------
spring.datasource.url=jdbc:mysql://localhost:3306/fin_advisor
spring.datasource.username=root
spring.datasource.password=Vikas@123

# ---------------- JPA Settings ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------- Server Settings ----------------
server.port=8085
spring.application.name=AI Personal Finance Advisor
# ---------------- Gemini AI Configuration ----------------
ai.api.key=AIzaSyBke47-yiIH3234IFozssyXmmV0uCDVCh4
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
